export const CART_ACTION_TYPES={
    'SET_IS_OPEN':'cart/SET_IS_OPEN',
    'SET_CART_ITEM':'cart/SET_CART_ITEM',
    'SET_CART_TOTAL':'cart/SET_CART_TOTAL',
    'SET_CART_COUNT':'cart/SET_CART_COUNT'
}